spring:
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
api:
  endpoint:
    base-url: /api/v1
